### ISSUE TITLE
problem with the 1.6.4 version of framework7

### ISSUE THREAD

**Issue by kkordinia** [valnub/Framework7-Plugin-Welcomescreen#22]
i tested this plugin with new versions of framework7 and it has a problem with tree new versions. when i call open function get this error:

> Uncaught TypeError: Cannot read property 'parallaxSlideElements' of undefined.

**Comment by valnub** [comment]
@razekteixeira Do you have any information that this is an issue on 1.6.4? Seems parallax related.

**Comment by valnub** [comment]
@kkordinia Did you test this in 1.6.2?

**Comment by kkordinia** [comment]
yes this plugin not work on 16.2, 16.3 and 16.4.

**Comment by razekteixeira** [comment]
@valnub I didn't noticed that but I'll test it and try to fix it asap ;)

**Comment by valnub** [comment]
@razekteixeira I updated to 1.6.4 and can confirm the issue. Definitely is a bug that needs to be fixed.

**Comment by valnub** [comment]
There seems to be something wrong with this line in the template:

`../../../../options.parallaxSlideElements`

Looks like options is undefined here

**Comment by razekteixeira** [comment]
@valnub yap, I spent about 15min checking the issue and I updated locally the F7 version. In fact the problem is with that ../../../../options.parallaxSlideElements.

For some reason it stopped working in this version and I didn't find out why until now. I'll check it later today ok?

**Comment by valnub** [comment]
@razekteixeira Yap, no problem. I'll also ask in chat. I know that there was a Dom7 issue in 1.6.3, maybe this is related.

**Comment by razekteixeira** [comment]
@valnub thanks, let's see that ;)

Regarding the possibility to change the template with options, I also checked it this afternoon and I think we could make something on the compilateTemplate method, maybe a try catch to check if the template passed in options is correct, with a fallback (catching the exception) to use the default one.

What do you think about this approach?

Thanks!

**Comment by valnub** [comment]
@razekteixeira From what I see, the error is in the default template.

Why is this there, btw?

`../../../../`

At other spots where options are used, this doesn't exist.

**Comment by razekteixeira** [comment]
@valnub yap the problem is there.

That `../../../../` is needed since we are trying to access the context variable "options" within an "each" loop. From the Template7 documentation, if we need to access a "parent" context variable within an "each loop" we need to use the ../

To be honest I'm not remembered why I did it that way, but it was for some reason lol :S

But today I tested it with "options" "../options" "../../options" and so on lol none of them worked...

I'll take a look ;) Thanks for the help

**Comment by valnub** [comment]
I was able to fix this be using this instead:

`{{@root.options.parallaxSlideElements.subtitle}}`

Still weird, though.

@kkordinia It should work now, can you download latest version of the plugin and tell us if the issue is gone? Thanks

**Comment by razekteixeira** [comment]
Damn it... I still don't get it... What the hell has changed to broke this? :S

Anyway, thanks a lot @valnub ;) Many many thanks ;) And sorry for that lol

**Comment by valnub** [comment]
@razekteixeira No problem. Could also be a bug in T7, so no worries ;-)

**Comment by razekteixeira** [comment]
@valnub I just made a PR. I had updated locally the F7 versions for js and css files.
I also updated the defaultTemplate:

- [ ] removed some {{#if options.parallaxTitle}} from there, totally useless :S lol
- [ ] added that @root.options...... on the parallax stuff...

I tested it with an older version of F7 and with the last version of F7. Everything seems to be ok, may you please take a look when you have some time?

All the best ;)
